theme:
    name: material
    features:
        - navigation.sections  # Sections are included in the navigation on the left.
        - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
        - header.autohide  # header disappears as you scroll
    palette:
        # Light mode / dark mode
        # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
        # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
        - scheme: default
          primary: white
          accent: amber
          toggle:
             icon: material/weather-night
             name: Switch to dark mode
        - scheme: slate
          primary: black
          accent: amber
          toggle:
             icon: material/weather-sunny
             name: Switch to light mode
    icon:
        repo: fontawesome/brands/github  # GitHub logo in top right
        logo: "material/duck"  # Quax logo in top left
    favicon: "_static/favicon.png"
    custom_dir: "docs/_overrides"  # Overriding part of the HTML

    # These additions are my own custom ones, having overridden a partial.
    twitter_bluesky_name: "@PatrickKidger"
    twitter_url: "https://twitter.com/PatrickKidger"
    bluesky_url: "https://PatrickKidger.bsky.social"

site_name: Quax
site_description: The documentation for the Quax software library.
site_author: Patrick Kidger
site_url: https://docs.kidger.site/quax

repo_url: https://github.com/patrick-kidger/quax
repo_name: patrick-kidger/quax
edit_uri: ""  # No edit button, as some of our pages are in /docs and some in /examples via symlink, so it's impossible for them all to be accurate

strict: true  # Don't allow warnings during the build process

extra_javascript: 
    # The below two make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
    - _static/mathjax.js
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - _static/custom_css.css

markdown_extensions:
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  # Allowing hidden expandable regions denoted by ???
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - admonition
    - toc:
        permalink: "¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4

plugins:
    - search:
        # See https://github.com/squidfunk/mkdocs-material/discussions/8116#discussioncomment-12632752
        # and https://github.com/patrick-kidger/equinox/issues/984
        # In particular this allows for searching e.g. 'filter_grad' and to match 'equinox.filter_grad'.
        separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
    - include_exclude_files:
        include:
            - ".htaccess"
        exclude:
            - "_overrides"
            - "examples/.ipynb_checkpoints"
    - ipynb
    - hippogriffe:
        extra_public_objects:
            - jax.core.AbstractValue
            - jax.extend.core.Primitive
    - mkdocstrings:
        handlers:
            python:
                options:
                    force_inspection: true
                    heading_level: 4
                    inherited_members: true
                    members_order: source
                    show_bases: false
                    show_if_no_docstring: true
                    show_overloads: false
                    show_root_heading: true
                    show_signature_annotations: true
                    show_source: false
                    show_symbol_type_heading: true
                    show_symbol_type_toc: true

nav:
    - 'index.md'
    - API:
        - 'api/quax.md'
        - 'api/lora.md'
    - Tutorials for custom Quax types:
        - 'Custom rules (introductory)': 'examples/custom_rules.ipynb'
        - 'Default rules (intermediate)': 'examples/default_rules.ipynb'
        - 'Redispatching (advanced)': 'examples/redispatch.ipynb'
        - 'examples/other.md'
